global:
    api-listen-addr: :5183
    timeout: 1m
    memo: sunnyduong#3509
    light-cache-size: 20
chains:
    gaia:
        type: cosmos
        value:
            key: KEYGAIA
            chain-id: GAIA
            rpc-addr: http://164.68.125.90:10004
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 1.5
            gas-prices: 0.001uatom
            debug: true
            timeout: 1m
            output-format: json
            sign-mode: sync
            type: native
            version: ics20-1
            order: UNORDERED
    stride:
        type: cosmos
        value:
            key: KEYSTRIDE
            chain-id: STRIDE-TESTNET-2
            rpc-addr: http://127.0.0.1:26657
            account-prefix: stride
            keyring-backend: test
            gas-adjustment: 1.5
            gas-prices: 0.001ustrd
            debug: true
            timeout: 1m
            output-format: json
            sign-mode: sync
            type: native
            version: ics20-1
            order: UNORDERED
paths:
    gaia-stride:
        src:
            chain-id: GAIA
            client-id: 07-tendermint-0
            connection-id: connection-0
            port-id: icacontroller-GAIA.DELEGATION,transfer,icacontriiler-GAIA.FEE,icacontroller-GAIA.WITHDRAWAL,icacontroller-GAIA.REDEMPTION
        dst:
            chain-id: STRIDE-TESTNET-2
            client-id: 07-tendermint-0
            connection-id: connection-0
            port-id: icahost,icacontroller-GAIA.DELEGATION,transfer,icacontriiler-GAIA.FEE,icacontroller-GAIA.WITHDRAWAL,icacontroller-GAIA.REDEMPTION
        src-channel-filter:
          rule: "allowlist"
          channel-list:
              - channel-0
              - channel-1
              - channel-2
              - channel-3
              - channel-4 
        dst-channel-filter:
          rule: "allowlist"
          channel-list:
              - channel-0
              - channel-1
              - channel-2
              - channel-3
              - channel-4 
